language: python
python:
  - 3.6
services: postgresql
env:
  global:
    - SECRET_KEY=SECRET_KEY
install:
  - make install
  - pip install coveralls
  - pip install psycopg2 --quiet
before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
script:
  - make test
after_success:
  - coveralls