version: "3"

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "80"
      - "443"
    depends_on:
      - db
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: Host:${MEDVET_HOST}
      traefik.port: "8000"
      caddy: ${MEDVET_HOST}
      caddy.reverse_proxy: "{{upstreams 8000}}"
volumes:
  postgres_data: